query getSLA($items: [ShippingItem], $code: String, $country: String) {
  shipping(items: $items, postalCode: $code, country: $country) {
    logisticsInfo {
      slas {
        shippingEstimate
        id
      }
    }
  }
}